@section('header')
<header>
    <div>
        <span>ロゴ部分</span>
        <span>検索ボックス</span>
        <span>ログイン</span>
        <span>会員登録</span>
        <span>出品</span>
    </div>
</header>
@endsection