@extends('layouts.app')

@section('css')
@endsection

@include('layouts.header')

@section('main')
<div>
    <div>
        商品画像
    </div>
    <div>
        <div>商品名</div>
        <div>金額</div>
    </div>
    <div>
        <span>支払い方法</span>
        <span>変更する</span>
    </div>
    <div>
        <span>支払い方法の内容</span>
    </div>
    <div>
        <span>配送先</span>
        <span>変更する</span>
    </div>
    <div>
        <span>配送先の内容</span>
    </div>
</div>
<div>
    <div>
        <div>
            <span>商品代金</span>
            <span>金額</span>
        </div>
        <div>
            <span>支払い金額</span>
            <span>金額</span>
        </div>
        <div>
            <span>支払い方法</span>
            <span>支払い方法の種類</span>
        </div>
    </div>
    <div><button class="button" type="submit">購入する</button></div>
</div>
@endsection